CREATE TABLE Produse (
    IDProdus INT PRIMARY KEY IDENTITY(1,1),
    Cod VARCHAR(10) UNIQUE NOT NULL,
    Nume NVARCHAR(100) NOT NULL,
    Tip NVARCHAR(50) NOT NULL,
    Pret DECIMAL(10,2) CHECK (Pret > 0),
    ContinutCiocolata INT,
    Ingrediente NVARCHAR(MAX),
    PentruDiabetici BIT DEFAULT 0,
    Stoc INT CHECK (Stoc >= 0),
    VolumVanzari INT DEFAULT 0
);

INSERT INTO Produse (Cod, Nume, Tip, Pret, ContinutCiocolata, Ingrediente, PentruDiabetici, Stoc, VolumVanzari)
VALUES
('BOM-VAN', 'Bomboane cu vanilie', 'Bomboane', 12.50, 0, 'Zahăr, sirop de glucoză, aromă vanilie', 0, 150, 200),
('CAR-IST', 'Caramele Istorisesti', 'Caramelă', 8.99, 0, 'Zahăr, miere, unt', 0, 80, 120),
('CIO-LUX', 'Ciocolată Lux 70%', 'Ciocolată', 25.00, 70, 'Cacao, zahăr, unt de cacao', 0, 50, 75),
('ZEF-ROZ', 'Zefir de culoare roz', 'Zefir', 15.99, 0, 'Albuș ou, zahăr, agar-agar, colorant natural', 0, 100, 90),
('BOM-DIAB', 'Bomboane fără zahăr', 'Bomboane', 18.00, 0, 'Maltitol, aromă de mentă', 1, 60, 85),
('CIO-ALB', 'Ciocolată albă', 'Ciocolată', 20.50, 0, 'Zahăr, unt de cacao, lapte praf', 0, 45, 60),
('TORT-FRU', 'Tort cu fructe', 'Tort', 120.00, 30, 'Făină, ouă, frișcă, fructe proaspete', 0, 10, 15),
('ING-LAM', 'Inghetată lamai', 'Înghețată', 9.99, 0, 'Lapte, zahăr, suc de lămâie', 0, 200, 180),
('PRJ-CAP', 'Prajitura Caprese', 'Prăjitură', 35.00, 0, 'Migdale, ciocolată neagră, ouă', 0, 25, 40),
('BOM-COCO', 'Bomboane cu cocos', 'Bomboane', 14.75, 0, 'Zahăr, cocos ras, sirop de glucoză', 0, 90, 110),
('CIO-FIN', 'Ciocolată cu alune', 'Ciocolată', 22.00, 55, 'Cacao, zahăr, alune, lapte', 0, 70, 95),
('MAR-FIN', 'Marțișoare cu ciocolată', 'Bomboane', 5.50, 40, 'Zahăr, ciocolată, colorant', 0, 300, 400),
('BOM-MENT', 'Bomboane cu mentă', 'Bomboane', 10.00, 0, 'Zahăr, ulei de mentă', 0, 120, 160),
('ING-CIO', 'Înghețată ciocolată', 'Înghețată', 12.00, 20, 'Lapte, cacao, zahăr', 0, 150, 130),
('TORT-CIO', 'Tort ciocolată belgiană', 'Tort', 150.00, 60, 'Ciocolată belgiană, frișcă, ouă', 0, 8, 12),
('ZEF-VER', 'Zefir verde', 'Zefir', 15.99, 0, 'Albuș ou, zahăr, agar-agar, colorant verde', 0, 75, 65),
('PRJ-FRU', 'Prăjitură cu fructe uscate', 'Prăjitură', 28.00, 0, 'Făină, ouă, stafide, nuci', 1, 40, 55),
('CAR-SAR', 'Caramele sărate', 'Caramelă', 7.50, 0, 'Zahăr, sare, unt', 0, 95, 110),
('CIO-ARO', 'Ciocolată cu aromă de portocale', 'Ciocolată', 24.00, 50, 'Cacao, zahăr, aromă naturală de portocale', 0, 55, 70),
('BOM-LAV', 'Bomboane cu lavandă', 'Bomboane', 16.00, 0, 'Zahăr, sirop de lavandă', 1, 65, 80),
('ING-DOV', 'Înghețată dovleac', 'Înghețată', 11.00, 0, 'Dovleac copt, lapte, miere', 1, 85, 90),
('TORT-DIA', 'Tort pentru diabetici', 'Tort', 130.00, 0, 'Făină integrală, zahăr înlocuitor, fructe', 1, 6, 10),
('PRJ-LEMN', 'Prăjitură cu lemn dulce', 'Prăjitură', 32.00, 0, 'Făină, miere, scorțișoară', 1, 30, 45),
('BOM-GHIM', 'Bomboane cu ghimber', 'Bomboane', 13.50, 0, 'Zahăr, sirop de ghimber', 0, 110, 140),
('CIO-MENT', 'Ciocolată cu mentă', 'Ciocolată', 23.50, 45, 'Cacao, ulei de mentă, zahăr', 0, 60, 85),
('CAR-ROSI', 'Caramele cu trandafiri', 'Caramelă', 9.00, 0, 'Zahăr, extract de trandafir', 0, 70, 95),
('ING-CAP', 'Înghețată căpșuni', 'Înghețată', 10.50, 0, 'Căpșuni proaspete, lapte, zahăr', 0, 180, 210),
('ZEF-ALB', 'Zefir alb', 'Zefir', 14.99, 0, 'Albuș ou, zahăr, agar-agar', 0, 85, 75),
('PRJ-NUCI', 'Prăjitură cu nuci', 'Prăjitură', 34.00, 0, 'Nuci, făină, miere', 1, 35, 50),
('BOM-ANAN', 'Bomboane cu ananas', 'Bomboane', 17.00, 0, 'Zahăr, suc de ananas', 0, 55, 70),
('CIO-COCO', 'Ciocolată cu cocos', 'Ciocolată', 21.00, 30, 'Cacao, zahăr, fulgi de cocos', 0, 65, 80),
('ING-VANI', 'Înghețată vanilie', 'Înghețată', 8.99, 0, 'Lapte, zahăr, extract de vanilie', 0, 220, 190),
('TORT-NUCI', 'Tort cu nuci și caramel', 'Tort', 140.00, 25, 'Nuci, caramel, făină', 0, 7, 11),
('CAR-MIER', 'Caramele cu miere', 'Caramelă', 10.00, 0, 'Miere, unt', 1, 88, 100),
('PRJ-DATL', 'Prăjitură cu curmale', 'Prăjitură', 30.00, 0, 'Curmale, făină integrală, nuci', 1, 28, 40),
('BOM-LAMA', 'Bomboane cu lămâie', 'Bomboane', 11.50, 0, 'Zahăr, suc de lămâie', 0, 130, 150),
('CIO-ROSI', 'Ciocolată cu trandafiri', 'Ciocolată', 26.00, 40, 'Cacao, extract de trandafir', 0, 40, 55),
('ING-CHOC', 'Înghețată cu chips de ciocolată', 'Înghețată', 13.50, 15, 'Lapte, ciocolată, zahăr', 0, 160, 140),
('ZEF-GALB', 'Zefir galben', 'Zefir', 15.99, 0, 'Albuș ou, zahăr, agar-agar, colorant galben', 0, 90, 80),
('PRJ-MIGD', 'Prăjitură cu migdale', 'Prăjitură', 36.00, 0, 'Migdale, miere, ouă', 1, 20, 35);

INSERT INTO Produse (Cod, Nume, Tip, Pret, ContinutCiocolata, Ingrediente, PentruDiabetici, Stoc, VolumVanzari)
VALUES
('BOM-LAV2', 'Bomboane cu extract de lavandă', 'Bomboane', 15.50, 0, 'Maltitol, ulei de lavandă', 1, 70, 90),
('CAR-CAF', 'Caramele cu cafea', 'Caramelă', 9.50, 0, 'Zahăr, extract de cafea, unt', 0, 60, 85),
('CIO-HAZ', 'Ciocolată cu alune de pădure', 'Ciocolată', 27.00, 65, 'Cacao, alune, zahăr', 0, 45, 60),
('ING-MOC', 'Înghețată cu aromă de mocca', 'Înghețată', 12.50, 10, 'Lapte, cafea, zahăr', 0, 130, 110),
('TORT-MIG', 'Tort cu migdale și caramel', 'Tort', 160.00, 20, 'Migdale, caramel, frișcă', 0, 5, 8),
('PRJ-QUIN', 'Prăjitură cu quinoa', 'Prăjitură', 40.00, 0, 'Quinoa, miere, ouă', 1, 25, 35),
('ZEF-VIO', 'Zefir violet', 'Zefir', 16.99, 0, 'Albuș ou, zahăr, agar-agar, colorant violet', 0, 65, 55),
('BOM-CRAN', 'Bomboane cu fructe de pădure', 'Bomboane', 19.00, 0, 'Zahăr, suc de fructe de pădure', 0, 85, 100),
('CIO-FND', 'Ciocolată fondant', 'Ciocolată', 29.00, 85, 'Cacao, zahăr, unt', 0, 30, 45),
('CAR-LAM', 'Caramele cu lămâie și mentă', 'Caramelă', 8.50, 0, 'Zahăr, suc de lămâie, mentă', 0, 95, 120),
('ING-MANG', 'Înghețată cu mango', 'Înghețată', 11.99, 0, 'Mango, lapte, zahăr', 0, 140, 160),
('PRJ-ORZ', 'Prăjitură cu fulgi de orz', 'Prăjitură', 28.50, 0, 'Fulgi de orz, miere, nuci', 1, 40, 55),
('BOM-PORT', 'Bomboane cu portocale', 'Bomboane', 14.00, 0, 'Zahăr, suc de portocale', 0, 110, 130),
('CIO-PIST', 'Ciocolată cu fistic', 'Ciocolată', 31.00, 50, 'Cacao, fistic, zahăr', 0, 35, 50),
('TORT-FND', 'Tort fondant cu fructe', 'Tort', 170.00, 40, 'Ciocolată fondant, fructe, frișcă', 0, 4, 7),
('ZEF-ARG', 'Zefir argintiu', 'Zefir', 17.50, 0, 'Albuș ou, zahăr brun, agar-agar', 0, 55, 45),
('CAR-GHIM', 'Caramele cu ghimber și miere', 'Caramelă', 10.50, 0, 'Miere, ghimber, unt', 1, 75, 95),
('ING-ROSI', 'Înghețată cu trandafiri', 'Înghețată', 13.99, 0, 'Petale de trandafir, lapte, zahăr', 0, 90, 75),
('PRJ-SECO', 'Prăjitură cu semințe de chia', 'Prăjitură', 37.00, 0, 'Semințe chia, făină integrală, miere', 1, 20, 30),
('BOM-MAR', 'Bomboane cu măr și scorțișoară', 'Bomboane', 16.50, 0, 'Zahăr, mere, scorțișoară', 0, 65, 80),
('CIO-LAM', 'Ciocolată cu lămâie', 'Ciocolată', 24.50, 35, 'Cacao, zahăr, ulei de lămâie', 0, 50, 65),
('TORT-MOC', 'Tort mocca cu nucă de cocos', 'Tort', 155.00, 25, 'Cafea, cocos, frișcă', 0, 6, 9),
('ING-AVET', 'Înghețată cu avocado și mentă', 'Înghețată', 14.50, 0, 'Avocado, mentă, lapte vegetal', 1, 80, 70),
('PRJ-AMAR', 'Prăjitură cu amarant', 'Prăjitură', 42.00, 0, 'Amarant, miere, nuci', 1, 15, 25),
('ZEF-CREM', 'Zefir crem cu vanilie', 'Zefir', 18.00, 0, 'Albuș ou, zahăr, vanilie', 0, 70, 60),
('BOM-ROSI', 'Bomboane trandafirii', 'Bomboane', 20.00, 0, 'Zahăr, extract de trandafir', 0, 45, 60),
('CAR-VANI', 'Caramele vanilie și migdale', 'Caramelă', 11.00, 0, 'Zahăr, vanilie, migdale', 0, 50, 65),
('CIO-COLA', 'Ciocolată cu cola', 'Ciocolată', 26.50, 45, 'Cacao, aromă de cola', 0, 40, 55),
('ING-BAN', 'Înghețată cu banană și caramel', 'Înghețată', 12.99, 15, 'Banană, caramel, lapte', 0, 120, 140),
('TORT-MAC', 'Tort macadamia și ciocolată', 'Tort', 180.00, 55, 'Nuci macadamia, ciocolată neagră', 0, 3, 5),
('PRJ-LIN', 'Prăjitură cu semințe de in', 'Prăjitură', 33.00, 0, 'Semințe de in, făină integrală, miere', 1, 28, 40),
('BOM-ZMEU', 'Bomboane cu aromă de zmeură', 'Bomboane', 17.50, 0, 'Zahăr, zmeură, sirop', 0, 95, 110),
('CIO-MINT', 'Ciocolată cu mentă și cocos', 'Ciocolată', 28.00, 40, 'Cacao, mentă, fulgi de cocos', 0, 55, 70),
('ING-COCO', 'Înghețată cu cocos și ananas', 'Înghețată', 13.50, 0, 'Cocon, ananas, lapte', 0, 100, 90),
('ZEF-AUR', 'Zefir auriu', 'Zefir', 19.99, 0, 'Albuș ou, zahăr, colorant alimentar auriu', 0, 40, 30),
('CAR-DUL', 'Caramele cu dulceată de prune', 'Caramelă', 9.99, 0, 'Dulceață de prune, zahăr', 0, 85, 100),
('PRJ-SUS', 'Prăjitură cu gutui', 'Prăjitură', 38.00, 0, 'Gutui, făină, miere', 1, 18, 22),
('BOM-PIER', 'Bomboane cu piersici', 'Bomboane', 18.50, 0, 'Zahăr, suc de piersică', 0, 75, 85),
('CIO-VAN', 'Ciocolată cu vanilie bourbon', 'Ciocolată', 30.00, 60, 'Cacao, vanilie bourbon, zahăr', 0, 25, 35);